server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /admin {
        try_files $uri $uri/ /index.html;
    }

        location = /auth-admin {
            internal;

            proxy_pass https://api.scxdrop.online/api/v1/admin/auth;

            proxy_pass_request_body off;
            proxy_set_header Content-Length "";

            proxy_set_header Cookie $http_cookie;
            proxy_set_header Authorization "Bearer $cookie_jwt";

            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Original-Method $request_method;
        }

        location @error401 {
            return 401;
        }

        location @error403 {
            return 403;
        }

    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public";
    }
}
